name: "Purge urls from QuantCDN"
description: "An action to Purge urls from QuantCDN"
author: "QuantCDN"
inputs:
  customer:
    description: "Your customer account name"
    required: true
  project:
    description: "Your project name"
    required: true
  token:
    description: "Your API token"
    required: true
  url_pattern:
    description: "The path pattern to purge"
    required: true
    default: ""
runs:
  using: "docker"
  image: "docker://quantcdn/cli:latest"
  entrypoint: quant
  args:
    - purge
    - ${{ inputs.url_pattern }}
    - -c ${{ inputs.customer }}
    - -t ${{ inputs.token }}
    - -p ${{ inputs.project }}
branding:
  icon: "upload-cloud"
  color: "blue"
